### ISSUE TITLE
.fnt格式的文件未能生成

### ISSUE THREAD

**Issue by Licken0602** [noword/EXAPUNKS-Localize#16]
您好。在寻找如何用日语玩EXAPUNKS的方法时，我发现了您们的翻译项目。我已经成功地使用了您们完成的补丁进行了中文化。非常感谢您们的出色项目。

现在我有一个问题。我尝试使用您们提供的源代码来制作日语化补丁，但在执行“run.bat”时遇到了问题。在生成字体文件的过程中，似乎嵌入了一个脚本，该脚本在Bitmap font generator中加载bmfc文件并创建fnt文件，但这个过程似乎没有成功。

当我执行“run.bat”时，Bitmap font generator的窗口会多次弹出，但从那之后，程序就没有任何进展了。当我尝试关闭Bitmap font generator的窗口时，命令提示符显示了以下错误：

FileNotFoundError: [Errno 2] No such file or directory: '77aa84e6-6089-42fa-90f7-2bce78d22f9e.fnt'
fnt = font_gen.gen()
^^^^^^^^^^^^^^
File "EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 165, in gen
fnt = Fnt(open(fnt_name, "r"))
^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '1a6c3ce9-5593-43a7-bc12-c755723dcceb.fnt'

看起来fnt文件的生成似乎没有成功。虽然bmfc文件已经成功生成，但我手动从Bitmap font generator加载bmfc文件并成功创建了fnt文件。但似乎bmfc文件的数量非常多，所以我认为手动操作是不现实的。

关于这个问题，您有什么解决方案可以建议吗？期待您的回复，谢谢。

**Comment by noword** [comment]
在 bmfont_gen.py 的 164 行 加一句 `print'"%s" -c %s -o %s' % (BMFONT_COM, bmfc_name, fnt_name)`

应该会有类似的输出 `[PATH]bmfont.com -c 1a6c3ce9-5593-43a7-bc12-c755723dcceb.bmfc -o 1a6c3ce9-5593-43a7-bc12-c755723dcceb.fnt`

在命令行下运行这条命令看看，出了什么错。

另外，你是日本人吗？你用chatgpt翻译的中文？

**Comment by Licken0602** [comment]
非常感谢您。我对编程几乎一无所知，所以您的帮助对我来说非常有价值。

按照您提供的指示，我在「bmfont_gen.py」中添加了相应的代码，并执行了命令。然后，我得到了以下的输出文本。看起来并没有出现任何错误。实际上，我也确认了在与「bmfont.com」相同的目录中成功生成了「1a6c3ce9-5593-43a7-bc12-c755723dcceb.fnt」文件。

Loading config.
Generating pages.
Saving font.
Finished.

关于您的问题，正如您所说，我是日本人。我使用了GPT4将日语翻译成中文。

**Comment by noword** [comment]
こんにちは。

你的python是什么版本？能否将 font\gen.py 的完整输出贴出来？

如果你对编程几乎一无所知，这个游戏可能并不适合你。

**Comment by Licken0602** [comment]
感谢您关于游戏的建议。我在“SHENZHEN I/O”游戏的第9关时放弃了，所以确实可能不适合我。不过，这只是一个爱好，所以我并不在意。

Python的版本似乎是3.11.1。输出结果似乎很长，这样真的没问题吗？

C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py:117: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  job.setDaemon(True)
fonts\archivo_black_16.5_5_v6.packedfont
fonts\archivo_black_24.0_5_v6.packedfont
fonts\archivo_black_58.0_5_v6.packedfont
fonts\devalencia_regular_48.0_5_v6.packedfont
fonts\impact_regular_27.0_5_v6.packedfont
fonts\karnivore_regular_29.0_5_v6.packedfont
fonts\michroma_regular_13.0_5_v6.packedfont
fonts\michroma_regular_18.0_5_v6.packedfont
fonts\archivo_black_33.0_5_v6.packedfont
fonts\dosis_semibold_34.0_5_v6.packedfont
fonts\karnivore_regular_50.0_5_v6.packedfont
fonts\michroma_regular_20.0_5_v6.packedfont
fonts\inconsolata_regular_14.0_3_v4.packedfont
fonts\devalencia_regular_40.0_5_v6.packedfont
fonts\michroma_regular_16.0_5_v6.packedfont
54.0 -11.0 64.0 64
64.0 -13.0 77.0 77
29.0 -7.0 35.0 35
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c ee83f1c4-63af-4ec3-8dd4-ad506bf39339.bmfc -o ee83f1c4-63af-4ec3-8dd4-ad506bf39339.fnt
20.0 -5.0 24.0 24
20.0 -5.0 24.0 24
31.0 -7.0 38.0 38
39.0 -10.0 48.0 48
24.0 -6.0 30.0 30
43.0 -6.0 49.0 49
12.0 -3.0 15.0 15
36.0 -8.0 44.0 44
46.0 -11.0 57.0 57
68.0 -17.0 84.0 84
28.0 -6.0 34.0 34
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c 73c1c0fc-953f-4e7d-a49f-cb1ee0ccac32.bmfc -o 73c1c0fc-953f-4e7d-a49f-cb1ee0ccac32.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c efb69282-9d9a-4b63-848e-8b8e1dd93bac.bmfc -o efb69282-9d9a-4b63-848e-8b8e1dd93bac.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c dbf3a122-7baa-470f-ba1a-c749688ec79e.bmfc -o dbf3a122-7baa-470f-ba1a-c749688ec79e.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c eb5c50bd-1c8d-4db7-ae59-115127d97a80.bmfc -o eb5c50bd-1c8d-4db7-ae59-115127d97a80.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c c3203e0a-e3e8-42e3-8382-8b9339913bd0.bmfc -o c3203e0a-e3e8-42e3-8382-8b9339913bd0.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c 31f5c6dd-d966-4b0e-ab72-9d010d66dbd8.bmfc -o 31f5c6dd-d966-4b0e-ab72-9d010d66dbd8.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c b13c88ac-26ce-4917-8ee6-2e6c0ff27c63.bmfc -o b13c88ac-26ce-4917-8ee6-2e6c0ff27c63.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c b21ae858-c74f-4a0c-829b-2a4b0dbf7faf.bmfc -o b21ae858-c74f-4a0c-829b-2a4b0dbf7faf.fnt
74.0 -10.0 84.0 84
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c 5afd952a-101b-438c-8b94-611aba86df84.bmfc -o 5afd952a-101b-438c-8b94-611aba86df84.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c f37a746b-6d28-4c1d-9aa9-74219c33cbc4.bmfc -o f37a746b-6d28-4c1d-9aa9-74219c33cbc4.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c f529b69f-24e7-4822-9bc8-5c50f9a993d0.bmfc -o f529b69f-24e7-4822-9bc8-5c50f9a993d0.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c 9b1ee561-ad76-46c8-b836-df686da07b68.bmfc -o 9b1ee561-ad76-46c8-b836-df686da07b68.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c 2c95700c-965b-44c3-9de3-2778f0f1c403.bmfc -o 2c95700c-965b-44c3-9de3-2778f0f1c403.fnt
"C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont.com" -c 803f03fe-ceeb-497d-8a7c-94a57821bbfc.bmfc -o 803f03fe-ceeb-497d-8a7c-94a57821bbfc.fnt
Exception in thread Thread-14 (fontgen_thread):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-6 (fontgen_thread):
Exception in thread Thread-11 (fontgen_thread):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-5 (fontgen_thread):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-2 (fontgen_thread):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-4 (fontgen_thread):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-10 (fontgen_thread):
Exception in thread Thread-3 (fontgen_thread):
Exception in thread Thread-8 (fontgen_thread):
Traceback (most recent call last):
Exception in thread Thread-13 (fontgen_thread):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Exception in thread Thread-15 (fontgen_thread):
Exception in thread Thread-9 (fontgen_thread):
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
    self.run()
Exception in thread Thread-1 (fontgen_thread):
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-7 (fontgen_thread):
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    do(name)
    self._target(*self._args, **self._kwargs)
    do(name)
    self.run()
    self._target(*self._args, **self._kwargs)
    do(name)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    fnt = font_gen.gen()
    fnt = font_gen.gen()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    fnt = font_gen.gen()
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    self.run()
    do(name)
    self._target(*self._args, **self._kwargs)
    do(name)
          ^^^^^^^^^^^^^^
    fnt = font_gen.gen()
          ^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    self._target(*self._args, **self._kwargs)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
Exception in thread Thread-12 (fontgen_thread):
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    self._target(*self._args, **self._kwargs)
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    fnt = font_gen.gen()
Traceback (most recent call last):
    fnt = font_gen.gen()
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
          ^^^^^^^^^^^^^^
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    do(name)
    fnt = font_gen.gen()
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    do(name)
    fnt = font_gen.gen()
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
          ^^^^^^^^^^^^^^
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    fnt = font_gen.gen()
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
    fnt = font_gen.gen()
    do(name)
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
    fnt = font_gen.gen()
    fnt = font_gen.gen()
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
    fnt = font_gen.gen()
    self.run()
    fnt = font_gen.gen()
          ^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
    self._target(*self._args, **self._kwargs)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 99, in fontgen_thread
    do(name)
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\gen.py", line 69, in do
    fnt = font_gen.gen()
          ^^^^^^^^^^^^^^
  File "C:\Users\EXAPUNKS-Localize-master\EXAPUNKS-Localize-master\font\bmfont\bmfont_gen.py", line 166, in gen
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
              ^^^^^^^^^^^^^^^^^^^
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
FileNotFoundError: [Errno 2] No such file or directory: 'efb69282-9d9a-4b63-848e-8b8e1dd93bac.fnt'
              ^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '9b1ee561-ad76-46c8-b836-df686da07b68.fnt'
              ^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'b21ae858-c74f-4a0c-829b-2a4b0dbf7faf.fnt'
FileNotFoundError: [Errno 2] No such file or directory: 'f529b69f-24e7-4822-9bc8-5c50f9a993d0.fnt'
    fnt = Fnt(open(fnt_name, "r"))
              ^^^^^^^^^^^^^^^^^^^
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
    fnt = Fnt(open(fnt_name, "r"))
              ^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '31f5c6dd-d966-4b0e-ab72-9d010d66dbd8.fnt'
              ^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '803f03fe-ceeb-497d-8a7c-94a57821bbfc.fnt'
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ee83f1c4-63af-4ec3-8dd4-ad506bf39339.fnt'
FileNotFoundError: [Errno 2] No such file or directory: '5afd952a-101b-438c-8b94-611aba86df84.fnt'
FileNotFoundError: [Errno 2] No such file or directory: 'dbf3a122-7baa-470f-ba1a-c749688ec79e.fnt'
              ^^^^^^^^^^^^^^^^^^^
    fnt = Fnt(open(fnt_name, "r"))
FileNotFoundError: [Errno 2] No such file or directory: 'c3203e0a-e3e8-42e3-8382-8b9339913bd0.fnt'
FileNotFoundError: [Errno 2] No such file or directory: 'eb5c50bd-1c8d-4db7-ae59-115127d97a80.fnt'
FileNotFoundError: [Errno 2] No such file or directory: '2c95700c-965b-44c3-9de3-2778f0f1c403.fnt'
              ^^^^^^^^^^^^^^^^^^^
              ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '73c1c0fc-953f-4e7d-a49f-cb1ee0ccac32.fnt'
FileNotFoundError: [Errno 2] No such file or directory: 'b13c88ac-26ce-4917-8ee6-2e6c0ff27c63.fnt'
FileNotFoundError: [Errno 2] No such file or directory: 'f37a746b-6d28-4c1d-9aa9-74219c33cbc4.fnt'

**Comment by noword** [comment]
看起来是 bmfont.com 没有正确运行，正常情况不应该弹出Bitmap font generator的窗口，只有在没有任何参数的情况下运行 bmfont.com 才会弹出窗口。也许 python 3.11 的 os.system 执行机制不一样了？

你的操作系统是什么版本？是在cmd下面运行run.bat的吗？另外，请把你的 chars.txt 传一下。

**Comment by Licken0602** [comment]
- Windows 11 版本 22H2（OS构建 22621.2361）
- 是的，我在CMD中运行了run.bat
- 明白了。如下所示发送给您。
[chars.txt](https://github.com/noword/EXAPUNKS-Localize/files/12866802/chars.txt)

**Comment by noword** [comment]
非常奇怪，我也不知道是什么原因。
os.system没有正常运行，也许是Python 3.11 或者 Windows 11 造成的。

**Comment by Licken0602** [comment]
非常感谢您的宝贵建议！我将bmfont_gen.py中的os.system替换为subprocess.call后，不知为何它开始正常工作了。非常感谢您这次的支持。真的非常感谢您。
